// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFgnyLFNq2lZ5s-KAdjYikTzcQgQeR0Lg',
    appId: '1:178202506405:web:e3e03fccb59e13a359494c',
    messagingSenderId: '178202506405',
    projectId: 'school-transport-system-6eb9f',
    authDomain: 'school-transport-system-6eb9f.firebaseapp.com',
    storageBucket: 'school-transport-system-6eb9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:178202506405:android:96bb433e91b8bbcd59494c',
    messagingSenderId: '178202506405',
    projectId: 'school-transport-system-6eb9f',
    storageBucket: 'school-transport-system-6eb9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIgPA6QI7qyC66rQx_kSlURX_JvvlfIBk',
    appId: '1:178202506405:ios:f5645c0f59fb385959494c',
    messagingSenderId: '178202506405',
    projectId: 'school-transport-system-6eb9f',
    storageBucket: 'school-transport-system-6eb9f.firebasestorage.app',
    iosClientId: '178202506405-1u2n9qdat4qjr9h1iv2g8v72bvt10emf.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolVanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIgPA6QI7qyC66rQx_kSlURX_JvvlfIBk',
    appId: '1:178202506405:ios:f5645c0f59fb385959494c',
    messagingSenderId: '178202506405',
    projectId: 'school-transport-system-6eb9f',
    storageBucket: 'school-transport-system-6eb9f.firebasestorage.app',
    iosClientId: '178202506405-1u2n9qdat4qjr9h1iv2g8v72bvt10emf.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolVanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFgnyLFNq2lZ5s-KAdjYikTzcQgQeR0Lg',
    appId: '1:178202506405:web:1d356f5c2e38960459494c',
    messagingSenderId: '178202506405',
    projectId: 'school-transport-system-6eb9f',
    authDomain: 'school-transport-system-6eb9f.firebaseapp.com',
    storageBucket: 'school-transport-system-6eb9f.firebasestorage.app',
  );
}
